In [820]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split

In [821]:
df = pd.read_csv('datasets\caracteres-limpo.csv', header=None)

df

0   1   2   3   4   5   6   7   8   9   ...  60  61  62  63  64  65  66  \
0   -1  -1   1   1  -1  -1  -1  -1  -1  -1  ...   1   1   1   1  -1  -1  -1   
1    1   1   1   1   1   1  -1  -1   1  -1  ...   1   1  -1  -1   1  -1  -1   
2   -1  -1   1   1   1   1   1  -1   1  -1  ...   1   1  -1  -1  -1   1  -1   
3    1   1   1   1   1  -1  -1  -1   1  -1  ...   1  -1  -1  -1  -1  -1   1   
4    1   1   1   1   1   1   1  -1   1  -1  ...   1   1   1  -1  -1  -1  -1   
5   -1  -1  -1   1   1   1   1  -1  -1  -1  ...   1  -1  -1  -1  -1  -1  -1   
6    1   1   1  -1  -1   1   1  -1   1  -1  ...  -1   1   1  -1  -1  -1  -1   
7   -1  -1  -1   1  -1  -1  -1  -1  -1  -1  ...  -1   1  -1   1  -1  -1  -1   
8    1   1   1   1   1   1  -1   1  -1  -1  ...   1   1  -1  -1   1  -1  -1   
9   -1  -1   1   1   1  -1  -1  -1   1  -1  ...   1  -1  -1  -1  -1   1  -1   
10   1   1   1   1   1  -1  -1   1  -1  -1  ...   1  -1  -1  -1  -1  -1   1   
11   1   1   1   1   1   1   1   1  -1  -1  ...   1   1   1  -1  -1  -1  -1   
12  -1  -1  -1  -1  -1   1  -1  -1  -1  -1  ...   1  -1  -1  -1  -1  -1  -1   
13   1  -1  -1  -1  -1   1  -1   1  -1  -1  ...  -1   1  -1  -1  -1  -1  -1   
14  -1  -1  -1   1  -1  -1  -1  -1  -1  -1  ...  -1   1   1   1  -1  -1  -1   
15   1   1   1   1   1   1  -1  -1   1  -1  ...   1   1  -1  -1   1  -1  -1   
16  -1  -1   1   1   1  -1   1  -1   1  -1  ...   1  -1  -1  -1  -1   1  -1   
17   1   1   1   1   1  -1  -1  -1   1  -1  ...   1  -1  -1  -1  -1  -1   1   
18   1   1   1   1   1   1   1  -1   1  -1  ...   1   1   1  -1  -1  -1  -1   
19  -1  -1  -1  -1   1   1   1  -1  -1  -1  ...   1  -1  -1  -1  -1  -1  -1   
20   1   1   1  -1  -1   1   1  -1   1  -1  ...  -1   1   1  -1  -1  -1  -1   

    67  68  69  
0   -1  -1  -1  
1   -1  -1  -1  
2   -1  -1  -1  
3   -1  -1  -1  
4    1  -1  -1  
5   -1   1  -1  
6   -1  -1   1  
7   -1  -1  -1  
8   -1  -1  -1  
9   -1  -1  -1  
10  -1  -1  -1  
11   1  -1  -1  
12  -1   1  -1  
13  -1  -1   1  
14  -1  -1  -1  
15  -1  -1  -1  
16  -1  -1  -1  
17  -1  -1  -1  
18   1  -1  -1  
19  -1   1  -1  
20  -1  -1   1  

[21 rows x 70 columns]

# Hiperparametros

## funções

In [822]:
Activations = {
    'tanh' : (lambda x: np.tanh(x))
    }
D_Activations = {
    'tanh' : (lambda x: 1-x**2)
    }
Errors = {
    'SR' : (lambda x,y: (x-y)**2)
    }
D_Errors = {
    'SR' : (lambda x,y: -2*(x-y))
    }

In [823]:
L0 = 63
L1 = 2
L2 = 7

learning_rate = 0.05
max_epochs = 1000

activation_func = Activations['tanh']
activation_deriv = D_Activations['tanh']

error_func = Errors['SR']
error_deriv = D_Errors['SR']

max_lim = 1
min_lim = -1

classes_number = 7

# Parametros

In [824]:
weights_L1 = [[]]
bias_L1 = []
weights_L2 = [[]]
bias_L2 = []

# implementação do algoritmo

## Inicialização dos pesos e viéses

In [825]:
def start_weights(i, j):
    weights = []
    for _ in range(j):
        temp = []
        for _ in range(i):
            temp.append(random.uniform(min_lim, max_lim))
        weights.append(temp)
    return np.array(weights)

In [826]:
def start_bias(j):
    bias = []
    for _ in range(j):
        bias.append(random.uniform(min_lim, max_lim))
    return np.array(bias)

## Feed forward

In [827]:
def feed_forward(x):
    temp = []

    output_L1 = []
    output_L2 = []

    for i,w in enumerate(weights_L1):
        temp = [X*W for (X, W) in zip(x, w)]
        temp = np.sum(temp) + bias_L1[i]
        output_L1.append(activation_func(temp))

    temp = []

    for i,w in enumerate(weights_L2):
        temp = [X*W for (X, W) in zip(output_L1, w)]
        temp = np.sum(temp) + bias_L2[i]
        output_L2.append(activation_func(temp))

    return np.array(output_L1), np.array(output_L2)
    

## calculo do erro total

In [828]:
def error_calculation(y, output_L2):
    total_error = 0
    for i in range(L2):
        SR = error_func(y[i], output_L2[i])
        total_error += SR
    return total_error

## back propagation

In [829]:
def back_propagation(x, y, output_L1, output_L2):
    # gradient descent L2
    delta_L2 = error_deriv(y, output_L2) * activation_deriv(output_L2)

    # updating weights and biases L2
    for i in range(L2):
        for j in range(L1):
            weights_L2[i][j] -= learning_rate * delta_L2[i] * output_L1[j]
            bias_L2[i] -= learning_rate * delta_L2[i]

    # gradient descent L1
    delta_L1 = []
    for v in weights_L2.T:
        delta_L1.append(np.sum(v*delta_L2))

    delta_L1 = delta_L1 * activation_deriv(output_L1)
    delta_L1 = np.array(delta_L1) 

    # updating weights adn biases L1
    for i in range(L1):
        for j in range(L0):
            weights_L1[i][j] -= (learning_rate * (delta_L1[i] * x[j]))
            bias_L1[i] -= (learning_rate * delta_L1[i])

    

## algoritmo de treinamento do modelo

In [830]:
def fit(X, Y):
    epoch = 0

    while epoch < max_epochs:
        for i in range(len(X.index)):
            x = np.array(X.iloc[i].values)
            y = np.array(Y.iloc[i].values)
            
            # feed forward
            output_L1, output_L2 = feed_forward(x)

            if i == 0:
                print(output_L2)

            # error calculation
            total_error = error_calculation(y, output_L2)

            # back propagation
            back_propagation(x, y, output_L1, output_L2)
        
        total_error = (total_error / len(X.index))

        epoch += 1

## algoritmo de teste

In [831]:
def predict(X):
    preds = []
    

    for i in range(len(X.index)):
        x = np.array(X.iloc[i].values)

        print(x)

        output_L1, output_L2 = feed_forward(x)

        preds.append(output_L2)

    return preds

# Uso da IA

## Separação de treino e teste

In [832]:
X = df.iloc[:,0:63]

X.head()

0   1   2   3   4   5   6   7   8   9   ...  53  54  55  56  57  58  59  \
0  -1  -1   1   1  -1  -1  -1  -1  -1  -1  ...  -1   1  -1   1   1   1  -1   
1   1   1   1   1   1   1  -1  -1   1  -1  ...  -1  -1   1   1   1   1   1   
2  -1  -1   1   1   1   1   1  -1   1  -1  ...  -1  -1   1  -1  -1   1   1   
3   1   1   1   1   1  -1  -1  -1   1  -1  ...  -1   1  -1   1   1   1   1   
4   1   1   1   1   1   1   1  -1   1  -1  ...  -1  -1   1   1   1   1   1   

   60  61  62  
0   1   1   1  
1   1   1  -1  
2   1   1  -1  
3   1  -1  -1  
4   1   1   1  

[5 rows x 63 columns]

In [833]:
y = df.iloc[:,63:70]

y.head()

63  64  65  66  67  68  69
0   1  -1  -1  -1  -1  -1  -1
1  -1   1  -1  -1  -1  -1  -1
2  -1  -1   1  -1  -1  -1  -1
3  -1  -1  -1   1  -1  -1  -1
4  -1  -1  -1  -1   1  -1  -1

In [834]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=7, stratify=y)

In [835]:
X_train

0   1   2   3   4   5   6   7   8   9   ...  53  54  55  56  57  58  59  \
16  -1  -1   1   1   1  -1   1  -1   1  -1  ...  -1   1  -1  -1  -1   1   1   
13   1  -1  -1  -1  -1   1  -1   1  -1  -1  ...   1  -1  -1   1  -1  -1  -1   
10   1   1   1   1   1  -1  -1   1  -1  -1  ...  -1   1  -1   1   1   1   1   
19  -1  -1  -1  -1   1   1   1  -1  -1  -1  ...  -1   1  -1  -1  -1   1   1   
3    1   1   1   1   1  -1  -1  -1   1  -1  ...  -1   1  -1   1   1   1   1   
9   -1  -1   1   1   1  -1  -1  -1   1  -1  ...  -1   1  -1  -1  -1   1   1   
11   1   1   1   1   1   1   1   1  -1  -1  ...  -1  -1  -1   1   1   1   1   
15   1   1   1   1   1   1  -1  -1   1  -1  ...  -1  -1   1   1   1   1   1   
8    1   1   1   1   1   1  -1   1  -1  -1  ...  -1  -1   1   1   1   1   1   
5   -1  -1  -1   1   1   1   1  -1  -1  -1  ...  -1   1  -1  -1  -1   1   1   
20   1   1   1  -1  -1   1   1  -1   1  -1  ...  -1   1  -1   1   1   1  -1   
18   1   1   1   1   1   1   1  -1   1  -1  ...  -1  -1   1   1   1   1   1   
7   -1  -1  -1   1  -1  -1  -1  -1  -1  -1  ...  -1   1  -1  -1   1  -1  -1   
14  -1  -1  -1   1  -1  -1  -1  -1  -1  -1  ...  -1  -1   1   1   1  -1  -1   

    60  61  62  
16   1  -1  -1  
13  -1   1  -1  
10   1  -1  -1  
19   1  -1  -1  
3    1  -1  -1  
9    1  -1  -1  
11   1   1   1  
15   1   1  -1  
8    1   1  -1  
5    1  -1  -1  
20  -1   1   1  
18   1   1   1  
7   -1   1  -1  
14  -1   1   1  

[14 rows x 63 columns]

In [836]:
X_test

0   1   2   3   4   5   6   7   8   9   ...  53  54  55  56  57  58  59  \
1    1   1   1   1   1   1  -1  -1   1  -1  ...  -1  -1   1   1   1   1   1   
2   -1  -1   1   1   1   1   1  -1   1  -1  ...  -1  -1   1  -1  -1   1   1   
17   1   1   1   1   1  -1  -1  -1   1  -1  ...  -1   1  -1   1   1   1   1   
0   -1  -1   1   1  -1  -1  -1  -1  -1  -1  ...  -1   1  -1   1   1   1  -1   
12  -1  -1  -1  -1  -1   1  -1  -1  -1  -1  ...  -1   1  -1  -1  -1   1   1   
6    1   1   1  -1  -1   1   1  -1   1  -1  ...  -1   1  -1   1   1   1  -1   
4    1   1   1   1   1   1   1  -1   1  -1  ...  -1  -1   1   1   1   1   1   

    60  61  62  
1    1   1  -1  
2    1   1  -1  
17   1  -1  -1  
0    1   1   1  
12   1  -1  -1  
6   -1   1   1  
4    1   1   1  

[7 rows x 63 columns]

In [837]:
y_train

63  64  65  66  67  68  69
16  -1  -1   1  -1  -1  -1  -1
13  -1  -1  -1  -1  -1  -1   1
10  -1  -1  -1   1  -1  -1  -1
19  -1  -1  -1  -1  -1   1  -1
3   -1  -1  -1   1  -1  -1  -1
9   -1  -1   1  -1  -1  -1  -1
11  -1  -1  -1  -1   1  -1  -1
15  -1   1  -1  -1  -1  -1  -1
8   -1   1  -1  -1  -1  -1  -1
5   -1  -1  -1  -1  -1   1  -1
20  -1  -1  -1  -1  -1  -1   1
18  -1  -1  -1  -1   1  -1  -1
7    1  -1  -1  -1  -1  -1  -1
14   1  -1  -1  -1  -1  -1  -1

In [838]:
y_test

63  64  65  66  67  68  69
1   -1   1  -1  -1  -1  -1  -1
2   -1  -1   1  -1  -1  -1  -1
17  -1  -1  -1   1  -1  -1  -1
0    1  -1  -1  -1  -1  -1  -1
12  -1  -1  -1  -1  -1   1  -1
6   -1  -1  -1  -1  -1  -1   1
4   -1  -1  -1  -1   1  -1  -1

## treinando

In [839]:
weights_L1 = start_weights(L0, L1)
bias_L1 = start_bias(L1)
weights_L2 = start_weights(L1, L2)
bias_L2 = start_bias(L2)

fit(X_train, y_train)

[-0.56851503  0.90646824 -0.42849708 -0.58642661 -0.94051522 -0.87631215
 -0.91291664]
[-0.6952458   0.31449964 -0.86834924 -0.91355013 -0.94184197 -0.89027913
 -0.89910349]
[-0.56134021 -0.68440956 -0.86041734 -0.89400049 -0.92544547 -0.85889313
 -0.87424968]
[-0.52613033 -0.73624262 -0.84755906 -0.87563472 -0.89993693 -0.82297311
 -0.82831056]
[-0.51234819 -0.73700177 -0.84770421 -0.86517787 -0.86237543 -0.79390627
 -0.8033235 ]
[-0.51420488 -0.74820264 -0.83759608 -0.87718622 -0.81432681 -0.77821519
 -0.77236422]
[-0.52731202 -0.7533063  -0.82937004 -0.88789728 -0.76998645 -0.77167966
 -0.76336961]
[-0.52916203 -0.75445838 -0.82286971 -0.89776839 -0.74295781 -0.76831967
 -0.76024788]
[-0.52745585 -0.75469174 -0.81905352 -0.90609585 -0.73059059 -0.76619428
 -0.75882947]
[-0.52384182 -0.75465123 -0.81737426 -0.91361192 -0.72523466 -0.76453323
 -0.75745883]
[-0.52055244 -0.75463128 -0.81675591 -0.92030695 -0.72265533 -0.76329111
 -0.75623416]
[-0.51961125 -0.75500604 -0.81630723 -0.925

[-0.52761218 -0.75806742 -0.80886491 -0.97532621 -0.71729691 -0.76180821
 -0.75792143]
[-0.52730305 -0.75799974 -0.8089227  -0.97543124 -0.71722141 -0.76170625
 -0.75791145]
[-0.52696343 -0.75792642 -0.80898992 -0.9755352  -0.71714034 -0.76159494
 -0.75790088]
[-0.52658792 -0.75784659 -0.8090681  -0.97563778 -0.7170527  -0.76147266
 -0.75788968]
[-0.52616984 -0.75775924 -0.80915921 -0.97573864 -0.71695733 -0.76133745
 -0.75787783]
[-0.52570087 -0.75766314 -0.80926578 -0.97583734 -0.71685278 -0.76118684
 -0.75786536]
[-0.52517059 -0.75755689 -0.80939107 -0.97593336 -0.71673728 -0.76101782
 -0.75785229]
[-0.52456601 -0.75743882 -0.80953931 -0.97602606 -0.71660869 -0.76082668
 -0.75783874]
[-0.52387097 -0.75730707 -0.80971594 -0.97611465 -0.71646445 -0.76060887
 -0.7578249 ]
[-0.52306558 -0.75715961 -0.80992789 -0.9761982  -0.71630146 -0.76035891
 -0.75781108]
[-0.52212599 -0.75699434 -0.81018385 -0.9762757  -0.71611616 -0.76007039
 -0.75779767]
[-0.52102494 -0.75680927 -0.81049411 -0.976

## testando

In [840]:
print(y_test)

    63  64  65  66  67  68  69
1   -1   1  -1  -1  -1  -1  -1
2   -1  -1   1  -1  -1  -1  -1
17  -1  -1  -1   1  -1  -1  -1
0    1  -1  -1  -1  -1  -1  -1
12  -1  -1  -1  -1  -1   1  -1
6   -1  -1  -1  -1  -1  -1   1
4   -1  -1  -1  -1   1  -1  -1


In [841]:
predict(X_test)

[ 1  1  1  1  1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1 -1  1 -1
 -1 -1 -1  1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1
  1 -1  1 -1 -1 -1 -1  1  1  1  1  1  1  1 -1]
[-1 -1  1  1  1  1  1 -1  1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1
 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1
 -1 -1  1 -1 -1 -1 -1  1 -1 -1  1  1  1  1 -1]
[ 1  1  1  1  1 -1 -1 -1  1 -1 -1 -1  1 -1 -1  1 -1 -1 -1 -1  1 -1  1 -1
 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1
  1 -1  1 -1 -1 -1  1 -1  1  1  1  1  1 -1 -1]
[-1 -1  1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1
 -1  1 -1 -1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1 -1 -1  1
 -1 -1  1 -1 -1 -1  1 -1  1  1  1 -1  1  1  1]
[-1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1
 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1 -1  1 -1 -1 -1  1
 -1 -1  1 -1 -1 -1  1 -1 -1 -1  1  1  1 -1 -1]
[ 1  1  1 -1 -1  1  1 -1  1 -1 -1  

[array([-0.60820855, -0.77338741, -0.82053324, -0.82093847, -0.73999115,
        -0.78198983, -0.78340349]),
 array([-0.60820855, -0.77338741, -0.82053324, -0.82093847, -0.73999115,
        -0.78198983, -0.78340349]),
 array([-0.60820872, -0.77338753, -0.82053324, -0.82093823, -0.73999125,
        -0.78198992, -0.78340357]),
 array([-0.60820855, -0.77338741, -0.82053324, -0.82093846, -0.73999115,
        -0.78198983, -0.78340349]),
 array([-0.60820855, -0.77338741, -0.82053324, -0.82093847, -0.73999115,
        -0.78198983, -0.78340349]),
 array([-0.60820855, -0.77338742, -0.82053324, -0.82093846, -0.73999116,
        -0.78198983, -0.78340349]),
 array([-0.60820855, -0.77338741, -0.82053324, -0.82093847, -0.73999115,
        -0.78198983, -0.78340349])]